#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cleanup() {
    echo "cleaning up..."
    kill -9 "$openvpn_pid"
    exit 0
}

# 打印启动使用的配置
echo "using openvpn conf file: $OV_CONF_PATH"
echo "using openvpn auth file: $OV_USER_PASS"

# OpenVPN Running.
mkdir /vpn/log
openvpn --config "$OV_CONF_PATH" "--auth-user-pass" "$OV_USER_PASS" &
openvpn_pid=$!

# 显示连接状况
while [[ ! -e /sys/class/net/tun0 ]]; do
    sleep 2 # 等待tun0出现，如果没有出现，说明openvpn启动失败
    if ! kill -0 "$openvpn_pid" 2>/dev/null; then
        echo "openvpn process not found, openvpn start failed."
        exit 1
    fi
done
echo "" && echo "tun0 is installed"

trap cleanup TERM

wait $openvpn_pid

