#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# 执行配置脚本，在启动前执行
if [[ -n "$WG_CONF_SHELL" ]]; then
    echo "create conf by shell: $WG_CONF_SHELL"
    eval "$WG_CONF_SHELL"
fi

# 启动wireguard
wg-quick up wg0
if [[ ! -e /sys/class/net/wg0 ]]; then
    echo "wg0 not found, wireguard up failed."
    exit 1
fi

# 显示连接状况
# sleep 1 && wg show
echo "" && echo "wg0 is up"

cleanup() {
    echo "wg0 is down"
    wg-quick down wg0
    kill -9 "$watch_pid"
    exit 0
}
trap cleanup TERM # HUP INT QUIT TERM

watch-conf &

watch_pid=$!
wait $watch_pid

# if [ ! -e /pause ]; then mkfifo /pause; fi
# </pause # 中断