#!/bin/bash

## ./myip
## where is my ip, 获取当前节点的公网ip地址， 包含了国家信息

## where is my ip, by cloudflare
## https://cloudflare.com/cdn-cgi/trace
xbody=$(curl -sSL -w "code=%{http_code}" "https://1.1.1.1/cdn-cgi/trace")
if [[ $xbody == *code=200 ]]; then
    echo "lc:$(echo "$xbody" | grep loc | cut -d= -f2)"
    echo "ip:$(echo "$xbody" | grep ip | cut -d= -f2)"
fi

## where is ip, by ipinfo.io
## https://ipinfo.io, https://ipinfo.io/ip,country,region,city,loc
# xbody=$(curl -sSL -w "code=%{http_code}" "https://ipinfo.io")
# if [[ $xbody == *code=200 ]]; then
#     echo "lc:$(echo "$xbody" | grep \"country\" | cut -d\" -f4)"
#     echo "ip:$(echo "$xbody" | grep \"ip\" | cut -d\" -f4)"
# fi
# # echo "xbody: $xbody"
