#!/bin/bash

# bash providers/surfshark/tool la-vte

host=$1
if [[ $host != *.prod.surfshark.com ]]; then
    host=$host".prod.surfshark.com"
fi

# 读取 server data
cat `dirname $0`/server.data | grep $host | while read line; do
    IFS=' ' read -r id connectionName publicKey tag location <<< "$line"
    if [[ ! ($tag == p* || $tag == v*)  ]]; then
        location=$tag" "$location
    fi

    if [[ "$2" == "ip" ]]; then
        ips=`curl -sSL -H 'Accept: application/dns-json' https://1.1.1.1/dns-query\?type\=A\&name\=$host`
        # echo "dns answer: $ips"
        # 如果不存在 Answer 则直接退出
        if [[ `echo $ips | jq '.Answer'` == "null" ]]; then
            echo "127.0.0.1 $publicKey $location"
            exit 0 # 没有IP则直接退出
        fi
        ip=`echo $ips | jq '.Answer | to_entries[] | .value.data' | head -n 1 | sed 's/"//g'`
        echo "$ip $publicKey $location" # 动态获取IP
    elif [[ "$2" == "" ]]; then 
        echo "$host $publicKey $location" # 默认使用域名
    else # "$2" =~ ^([0-9]+\.){3}[0-9]+$
        echo "$2 $publicKey $location" # 指定固定IP
    fi
    exit 0 # 只输出一信息即可
done
